// AUTO-GENERATED by qa-buttons-fix.ts — do not edit manually
import { test } from '@playwright/test'
import { rows } from './button-smoke.config'

const BASE_URL = 'https://ingredientbot.com'
const ROW_TIMEOUT_MS = 10000

function tryParse(s: string): Record<string, unknown> | null {
  try { return JSON.parse(s) } catch { return null }
}

for (const row of rows) {
  test(`CTA: ${row.route} | ${row.cta}`, async ({ page }) => {
    const apiResponses: Array<{ url: string; status: number; body: string }> = []
    const consoleErrors: string[] = []

    page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text().slice(0, 400)) })
    page.on('pageerror', err => consoleErrors.push(String(err).slice(0, 400)))

    page.on('response', async (res) => {
      try {
        const u = new URL(res.url())
        if (!u.pathname.startsWith('/api/') || u.pathname.startsWith('/api/auth/') || u.pathname.startsWith('/_next/')) return
        const body = await res.text().catch(() => '')
        apiResponses.push({ url: u.pathname, status: res.status(), body })
      } catch { /* ignore */ }
    })

    // Navigate
    await page.goto(BASE_URL + row.route)

    // Detect coming-soon / auth redirect
    const finalUrl = page.url()
    if (finalUrl.includes('/coming-soon') || (finalUrl.includes('/login') && !row.route.startsWith('/login'))) {
      throw new Error(JSON.stringify({ kind: 'redirected', url: finalUrl, message: 'page redirected — site may be gated or in coming-soon mode' }))
    }

    if (row.fill) await row.fill(page)

    // Find and click the CTA
    const btns = page.getByRole('button', { name: row.cta, exact: false })
    const btnCount = await btns.count()
    if (btnCount === 0) {
      throw new Error(JSON.stringify({ kind: 'missing-testid', message: `button "${row.cta}" not found on ${row.route}` }))
    }
    await btns.first().click()

    // Wait for API response, result testid, or timeout
    await new Promise<void>(resolve => {
      const interval = setInterval(() => { if (apiResponses.length > 0) { clearInterval(interval); resolve() } }, 150)
      setTimeout(() => { clearInterval(interval); resolve() }, ROW_TIMEOUT_MS)
    })
    if (row.expectResultTestId) {
      await page.getByTestId(row.expectResultTestId).waitFor({ state: 'visible', timeout: 5000 }).catch(() => {})
    }

    // Classify failures from captured API responses
    for (const r of apiResponses) {
      const b = tryParse(r.body)
      if (r.status === 401) throw new Error(JSON.stringify({ kind: 'middleware-401', apiPath: r.url, status: r.status, responseBody: r.body.slice(0, 500) }))
      if (r.status === 400) throw new Error(JSON.stringify({ kind: 'schema-400', apiPath: r.url, status: r.status, responseBody: r.body.slice(0, 500), fieldErrors: (b as any)?.error?.issues ?? (b as any)?.fieldErrors ?? null }))
      if (r.status === 404 || r.status === 405) throw new Error(JSON.stringify({ kind: 'route-404-405', apiPath: r.url, status: r.status, responseBody: r.body.slice(0, 300) }))
      if (r.status >= 500) throw new Error(JSON.stringify({ kind: '5xx', apiPath: r.url, status: r.status, responseBody: r.body.slice(0, 500) }))
      if (r.status === 200 && b && typeof (b as any).error === 'string') throw new Error(JSON.stringify({ kind: 'swallowed-error', apiPath: r.url, status: r.status, responseBody: r.body.slice(0, 500) }))
    }

    // Unhandled browser errors (no API call made)
    if (apiResponses.length === 0 && consoleErrors.length > 0) {
      throw new Error(JSON.stringify({ kind: 'client-error', message: consoleErrors[0] }))
    }
  })
}
