import { notFound } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { cache } from 'react'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Clock, Users, ChefHat, ArrowRight, Utensils } from 'lucide-react'
import { safeJsonLdString } from '@/lib/utils'
import { AllergenDisclaimer } from '@/components/allergen-disclaimer'
import { CookThisButton } from '@/components/recipe/cook-this-button'
import { AllergyAwarenessNotice } from '@/components/allergy-awareness-notice'
import { allergenLabel } from '@/lib/allergens'
import { formatDuration, isIngredientHeading } from '@/lib/recipe-format'

export const revalidate = 3600

interface Props {
  params: Promise<{ slug: string }>
}

// cache() deduplicates the DB call between generateMetadata and the page render within the same request
const getPublicRecipe = cache((slug: string) =>
  prisma.recipe.findUnique({ where: { publicSlug: slug, isPublic: true } })
)

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://ingredientbot.com'

// Generate OG metadata for social sharing previews
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const recipe = await getPublicRecipe(slug)

  if (!recipe) return { title: 'Recipe Not Found' }

  const description = recipe.description ?? `A recipe generated by IngredientBot AI`

  return {
    title: `${recipe.title} — IngredientBot`,
    description,
    alternates: {
      canonical: `${baseUrl}/r/${slug}`,
    },
    openGraph: {
      title: recipe.title,
      description,
      siteName: 'IngredientBot',
      images: [{ url: '/opengraph-image', width: 1200, height: 630 }],
    },
    twitter: {
      card: 'summary_large_image',
      title: recipe.title,
      description,
    },
  }
}

export default async function PublicRecipePage({ params }: Props) {
  const { slug } = await params

  const recipe = await getPublicRecipe(slug)

  if (!recipe) notFound()

  // One query — related public recipes for the cross-link strip (same cuisine
  // when known, newest otherwise). Gives share pages internal links to /recipes.
  const related = await prisma.recipe.findMany({
    where: {
      isPublic: true,
      publicSlug: { not: null },
      id: { not: recipe.id },
      ...(recipe.cuisine ? { cuisine: recipe.cuisine } : {}),
    },
    select: {
      publicSlug: true,
      title: true,
      cuisine: true,
      difficulty: true,
      prepTimeMin: true,
      cookTimeMin: true,
    },
    orderBy: { updatedAt: 'desc' },
    take: 4,
  })

  // recipeData is typed as Json in Prisma — cast to known shape
  const data = recipe.recipeData as {
    title: string
    description: string
    servings: number
    prepTimeMin?: number
    cookTimeMin?: number
    cuisine?: string
    difficulty?: string
    ingredients: { name: string; amount: string; unit: string }[]
    steps: string[]
    notes?: string
    nutrition?: { calories: number; protein: number; fat: number; carbs: number; fiber: number }
  }

  const totalMin = (recipe.prepTimeMin ?? 0) + (recipe.cookTimeMin ?? 0)

  const hasAllergenInfo =
    recipe.allergens.length > 0 || recipe.mayContain.length > 0 || recipe.allergenNotes != null

  const difficultyColor: Record<string, string> = {
    easy: 'bg-[hsl(var(--color-success-muted))] text-[hsl(var(--color-success-fg))]',
    medium: 'bg-[hsl(var(--color-warning-muted))] text-[hsl(var(--color-warning-fg))]',
    hard: 'bg-destructive/10 text-destructive',
  }

  // Build schema.org Recipe structured data for Google Rich Results
  const recipeJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Recipe',
    name: data.title,
    description: data.description ?? undefined,
    // Section labels are dropped — Google would otherwise index "For the broth
    // and tare" as an ingredient of the dish.
    recipeIngredient: data.ingredients
      ?.filter((ing) => !isIngredientHeading(ing))
      .map((ing) => `${ing.amount} ${ing.unit} ${ing.name}`.trim()),
    recipeInstructions: data.steps?.map((step, i) => ({
      '@type': 'HowToStep',
      position: i + 1,
      text: step,
    })),
    recipeYield: data.servings ? String(data.servings) : undefined,
    prepTime: recipe.prepTimeMin ? `PT${recipe.prepTimeMin}M` : undefined,
    cookTime: recipe.cookTimeMin ? `PT${recipe.cookTimeMin}M` : undefined,
    totalTime: totalMin > 0 ? `PT${totalMin}M` : undefined,
    recipeCuisine: recipe.cuisine ?? undefined,
    keywords: recipe.tags?.join(', ') || undefined,
    nutrition: data.nutrition
      ? {
          '@type': 'NutritionInformation',
          calories: `${data.nutrition.calories} calories`,
          proteinContent: `${data.nutrition.protein}g`,
          carbohydrateContent: `${data.nutrition.carbs}g`,
          fatContent: `${data.nutrition.fat}g`,
          fiberContent: data.nutrition.fiber != null ? `${data.nutrition.fiber}g` : undefined,
        }
      : undefined,
    author: {
      '@type': 'Organization',
      name: 'IngredientBot',
      url: baseUrl,
    },
    url: `${baseUrl}/r/${recipe.publicSlug}`,
  }

  return (
    <div className="min-h-screen bg-background">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLdString(recipeJsonLd) }}
      />
      {/* Minimal nav — no auth required */}
      <header className="border-b border-border bg-card/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 text-sm font-semibold text-foreground hover:text-primary transition-colors">
            <ChefHat className="h-5 w-5 text-primary" />
            IngredientBot
          </Link>
          <Button asChild size="sm">
            <Link href="/kitchen">
              Try it free
              <ArrowRight className="h-3.5 w-3.5 ml-1.5" />
            </Link>
          </Button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8">
        {/* Title block */}
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-foreground mb-2 text-balance">{data.title}</h1>
          {data.description && (
            <p className="text-muted-foreground text-lg leading-relaxed">{data.description}</p>
          )}
          <div className="flex flex-wrap gap-2 mt-4">
            {recipe.cuisine && <Badge variant="secondary">{recipe.cuisine}</Badge>}
            {recipe.difficulty && (
              <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${difficultyColor[recipe.difficulty] ?? ''}`}>
                {recipe.difficulty}
              </span>
            )}
            {totalMin > 0 && (
              <span className="inline-flex items-center gap-1.5 text-sm text-muted-foreground">
                <Clock className="h-4 w-4" />
                {formatDuration(totalMin)}
              </span>
            )}
            {recipe.servings && (
              <span className="inline-flex items-center gap-1.5 text-sm text-muted-foreground">
                <Users className="h-4 w-4" />
                {recipe.servings} servings
              </span>
            )}
          </div>
        </div>

        <div className="grid gap-8 md:grid-cols-[1fr_2fr]">
          {/* Ingredients */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
              <Utensils className="h-4 w-4 text-primary" />
              Ingredients
            </h2>
            <ul className="space-y-2">
              {data.ingredients?.map((ing, i) =>
                isIngredientHeading(ing) ? (
                  // Multi-component dishes ship "For the broth"-style labels in the
                  // ingredient array; as a plain bullet they read as a broken row.
                  <li
                    key={i}
                    className="pt-3 first:pt-0 text-xs font-semibold uppercase tracking-wide text-foreground"
                  >
                    {ing.name.replace(/^for\s+(the\s+)?/i, '')}
                  </li>
                ) : (
                  <li key={i} className="flex items-baseline gap-2 text-sm">
                    <span className="font-medium text-foreground whitespace-nowrap">
                      {ing.amount} {ing.unit}
                    </span>
                    <span className="text-muted-foreground">{ing.name}</span>
                  </li>
                ),
              )}
            </ul>

            {/* Allergens — rendered only alongside the safety disclaimer; the
                data is dual-model verified but absence of a flag is still never
                an allergen-free guarantee (three-state: contains / may contain / absent). */}
            {hasAllergenInfo && (
              <div className="mt-6 rounded-lg border border-border bg-muted/30 p-4" data-testid="recipe-allergen-info">
                <h3 className="text-sm font-semibold text-foreground mb-2">Allergen information</h3>
                {recipe.allergens.length > 0 && (
                  <div className="mb-2">
                    <p className="text-xs font-medium text-muted-foreground mb-1.5">Contains</p>
                    <div className="flex flex-wrap gap-1.5">
                      {recipe.allergens.map((a) => (
                        <Badge key={a} variant="secondary" className="bg-destructive/10 text-destructive hover:bg-destructive/10">
                          {allergenLabel(a)}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}
                {recipe.mayContain.length > 0 && (
                  <div className="mb-2">
                    <p className="text-xs font-medium text-muted-foreground mb-1.5">May contain</p>
                    <div className="flex flex-wrap gap-1.5">
                      {recipe.mayContain.map((a) => (
                        <Badge key={a} variant="secondary">
                          {allergenLabel(a)}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}
                {recipe.allergenNotes && (
                  <p className="text-xs text-muted-foreground mb-2">{recipe.allergenNotes}</p>
                )}
                <p className="text-xs text-muted-foreground">
                  Only the allergens listed above were checked. An allergen not being listed is{' '}
                  <span className="font-medium text-foreground">not</span> a guarantee that it is absent.
                </p>
              </div>
            )}

            {/* Unconditional safety notice — recipes with NO allergen fields are
                exactly the ones where annotation never ran, so absence of data
                must never mean absence of warning. */}
            <AllergenDisclaimer compact className={hasAllergenInfo ? 'mt-3' : 'mt-6'} />

            {/* Nutrition */}
            {data.nutrition && (
              <div className="mt-6 rounded-lg border border-border bg-muted/30 p-4">
                <h3 className="text-sm font-semibold text-foreground mb-2">Per serving (estimated)</h3>
                <div className="grid grid-cols-2 gap-2 text-xs text-muted-foreground">
                  <span>{data.nutrition.calories} kcal</span>
                  <span>{data.nutrition.protein}g protein</span>
                  <span>{data.nutrition.carbs}g carbs</span>
                  <span>{data.nutrition.fat}g fat</span>
                  {data.nutrition.fiber != null && <span>{data.nutrition.fiber}g fiber</span>}
                </div>
              </div>
            )}
          </section>

          {/* Instructions */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Instructions</h2>
            <ol className="space-y-4">
              {data.steps?.map((step, i) => (
                <li key={i} className="flex gap-3">
                  <span className="flex-shrink-0 h-6 w-6 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center mt-0.5">
                    {i + 1}
                  </span>
                  <p className="text-sm text-foreground leading-relaxed">{step}</p>
                </li>
              ))}
            </ol>
            {data.notes && (
              <div className="mt-6 rounded-lg border-l-4 border-primary/40 bg-muted/30 px-4 py-3">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1">Notes</p>
                <p className="text-sm text-foreground">{data.notes}</p>
              </div>
            )}
          </section>
        </div>

        {/* Related recipes — internal cross-links between public recipe pages */}
        {related.length > 0 && (
          <section className="mt-12" data-testid="recipe-related-strip">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-foreground">
                More {recipe.cuisine ? `${recipe.cuisine} ` : ''}recipes
              </h2>
              <Link
                href="/recipes"
                className="text-sm text-primary hover:underline underline-offset-4 inline-flex items-center gap-1"
              >
                Browse all
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              {related.map((r) => (
                <Link
                  key={r.publicSlug}
                  href={`/r/${r.publicSlug}`}
                  className="group rounded-lg border border-border bg-card p-4 hover:border-primary/40 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  data-testid="recipe-related-card"
                >
                  <h3 className="text-sm font-semibold text-foreground group-hover:text-primary transition-colors line-clamp-2 text-balance">
                    {r.title}
                  </h3>
                  <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                    {r.cuisine && <Badge variant="secondary" className="text-xs">{r.cuisine}</Badge>}
                    {(r.prepTimeMin ?? 0) + (r.cookTimeMin ?? 0) > 0 && (
                      <span className="inline-flex items-center gap-1">
                        <Clock className="h-3 w-3" />
                        {(r.prepTimeMin ?? 0) + (r.cookTimeMin ?? 0)} min
                      </span>
                    )}
                  </div>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* CTA */}
        <div className="mt-12 rounded-2xl border border-primary/20 bg-primary/5 p-6 text-center">
          <ChefHat className="h-8 w-8 text-primary mx-auto mb-3" />
          <h2 className="text-xl font-bold text-foreground mb-2">Make it yours</h2>
          <p className="text-muted-foreground text-sm mb-4 max-w-sm mx-auto">
            Add this to your recipes and you can make it vegetarian, scale the servings, or swap
            an ingredient you do not have.
          </p>
          {/* Adds the recipe to the visitor's own collection — the AI modifiers are
              owner-scoped, so they cannot run against the house library account. */}
          <CookThisButton recipeId={recipe.id} slug={slug} />
        </div>
      </main>

      <footer className="border-t border-border py-6 text-center text-sm text-muted-foreground">
        <AllergyAwarenessNotice className="mb-5 px-4" />
        <div className="flex items-center justify-center gap-4">
          <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
          <Link href="/recipes" className="hover:text-foreground transition-colors">Recipes</Link>
          <Link href="/ingredients" className="hover:text-foreground transition-colors">Ingredients</Link>
          <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
          <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
        </div>
      </footer>
    </div>
  )
}
