import { notFound } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Clock, Users, ChefHat, ArrowRight, Utensils } from 'lucide-react'

interface Props {
  params: Promise<{ slug: string }>
}

// Generate OG metadata for social sharing previews
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const recipe = await prisma.recipe.findUnique({
    where: { publicSlug: slug, isPublic: true },
    select: { title: true, description: true, cuisine: true },
  })

  if (!recipe) return { title: 'Recipe Not Found' }

  return {
    title: `${recipe.title} — IngredientBot`,
    description: recipe.description ?? `A recipe generated by IngredientBot AI`,
    openGraph: {
      title: recipe.title,
      description: recipe.description ?? `A recipe generated by IngredientBot AI`,
      siteName: 'IngredientBot',
    },
    twitter: {
      card: 'summary',
      title: recipe.title,
      description: recipe.description ?? undefined,
    },
  }
}

export default async function PublicRecipePage({ params }: Props) {
  const { slug } = await params

  const recipe = await prisma.recipe.findUnique({
    where: { publicSlug: slug, isPublic: true },
  })

  if (!recipe) notFound()

  // recipeData is typed as Json in Prisma — cast to known shape
  const data = recipe.recipeData as {
    title: string
    description: string
    servings: number
    prepTimeMin?: number
    cookTimeMin?: number
    cuisine?: string
    difficulty?: string
    ingredients: { name: string; amount: string; unit: string }[]
    steps: string[]
    notes?: string
    nutrition?: { calories: number; protein: number; fat: number; carbs: number; fiber: number }
  }

  const totalMin = (recipe.prepTimeMin ?? 0) + (recipe.cookTimeMin ?? 0)

  const difficultyColor: Record<string, string> = {
    easy: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
    medium: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
    hard: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Minimal nav — no auth required */}
      <header className="border-b border-border bg-card/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 text-sm font-semibold text-foreground hover:text-primary transition-colors">
            <ChefHat className="h-5 w-5 text-primary" />
            IngredientBot
          </Link>
          <Button asChild size="sm">
            <Link href="/kitchen">
              Try it free
              <ArrowRight className="h-3.5 w-3.5 ml-1.5" />
            </Link>
          </Button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8">
        {/* Title block */}
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-foreground mb-2 text-balance">{data.title}</h1>
          {data.description && (
            <p className="text-muted-foreground text-lg leading-relaxed">{data.description}</p>
          )}
          <div className="flex flex-wrap gap-2 mt-4">
            {recipe.cuisine && <Badge variant="secondary">{recipe.cuisine}</Badge>}
            {recipe.difficulty && (
              <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${difficultyColor[recipe.difficulty] ?? ''}`}>
                {recipe.difficulty}
              </span>
            )}
            {totalMin > 0 && (
              <span className="inline-flex items-center gap-1.5 text-sm text-muted-foreground">
                <Clock className="h-4 w-4" />
                {totalMin} min
              </span>
            )}
            {recipe.servings && (
              <span className="inline-flex items-center gap-1.5 text-sm text-muted-foreground">
                <Users className="h-4 w-4" />
                {recipe.servings} servings
              </span>
            )}
          </div>
        </div>

        <div className="grid gap-8 md:grid-cols-[1fr_2fr]">
          {/* Ingredients */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
              <Utensils className="h-4 w-4 text-primary" />
              Ingredients
            </h2>
            <ul className="space-y-2">
              {data.ingredients?.map((ing, i) => (
                <li key={i} className="flex items-baseline gap-2 text-sm">
                  <span className="font-medium text-foreground whitespace-nowrap">
                    {ing.amount} {ing.unit}
                  </span>
                  <span className="text-muted-foreground">{ing.name}</span>
                </li>
              ))}
            </ul>

            {/* Nutrition */}
            {data.nutrition && (
              <div className="mt-6 rounded-lg border border-border bg-muted/30 p-4">
                <h3 className="text-sm font-semibold text-foreground mb-2">Per serving</h3>
                <div className="grid grid-cols-2 gap-2 text-xs text-muted-foreground">
                  <span>{data.nutrition.calories} kcal</span>
                  <span>{data.nutrition.protein}g protein</span>
                  <span>{data.nutrition.carbs}g carbs</span>
                  <span>{data.nutrition.fat}g fat</span>
                  {data.nutrition.fiber != null && <span>{data.nutrition.fiber}g fiber</span>}
                </div>
              </div>
            )}
          </section>

          {/* Instructions */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Instructions</h2>
            <ol className="space-y-4">
              {data.steps?.map((step, i) => (
                <li key={i} className="flex gap-3">
                  <span className="flex-shrink-0 h-6 w-6 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center mt-0.5">
                    {i + 1}
                  </span>
                  <p className="text-sm text-foreground leading-relaxed">{step}</p>
                </li>
              ))}
            </ol>
            {data.notes && (
              <div className="mt-6 rounded-lg border-l-4 border-primary/40 bg-muted/30 px-4 py-3">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1">Notes</p>
                <p className="text-sm text-foreground">{data.notes}</p>
              </div>
            )}
          </section>
        </div>

        {/* CTA */}
        <div className="mt-12 rounded-2xl border border-primary/20 bg-primary/5 p-6 text-center">
          <ChefHat className="h-8 w-8 text-primary mx-auto mb-3" />
          <h2 className="text-xl font-bold text-foreground mb-2">Cook smarter with IngredientBot</h2>
          <p className="text-muted-foreground text-sm mb-4 max-w-sm mx-auto">
            Enter the ingredients you have and get AI-generated recipes instantly — free to try.
          </p>
          <Button asChild size="lg">
            <Link href="/kitchen">
              Try IngredientBot Free
              <ArrowRight className="h-4 w-4 ml-2" />
            </Link>
          </Button>
        </div>
      </main>
    </div>
  )
}
