/**
 * Allergen annotation for batch seed/backfill scripts.
 *
 * SINGLE-MODEL as of 2026-08-05 (was a dual-model Azure + claude-opus-5 gate).
 * Allergen sets are now generated by the same paid Azure frontier model every
 * other seeder on this site uses — `tier: 'quality'` → gpt-5.4 — with no
 * independent second-model cross-check.
 *
 * What that changes, stated plainly: this output is a single model's guess.
 * It is NOT verified. Nothing here may be presented to a user as a confirmed
 * allergen-free result. The Recipe timestamp column was renamed
 * `allergenVerifiedAt` → `allergenAnnotatedAt` to match (see prisma/schema.prisma).
 *
 * What has NOT changed, and must not:
 *   - Generation stays on a PAID FRONTIER model. `providers: ['azure']` with
 *     no fallback of any kind — never the free Cerebras/Groq gpt-oss-120b
 *     lane, never Gemini. Missing Azure env fails closed with an error rather
 *     than silently downgrading.
 *   - The visible allergen disclaimer at src/components/allergen-disclaimer.tsx
 *     (testid `allergen-disclaimer`) must render anywhere these fields are
 *     shown. It names the two failure modes a model cannot see: a misclassified
 *     ingredient, and cross-contamination in the product actually bought.
 *   - The runtime lane in src/lib/ai.ts is untouched by this file.
 *
 * Three-state honesty is retained: `contains` / `may contain` / absent.
 * Absence of a flag is never a "free from X" claim, and callers must render it
 * that way.
 *
 * Vocabulary is the canonical FDA top-9 + EU-14 union in src/lib/allergens.ts.
 */
import { z } from 'zod'
import { batchObject } from './ai-batch'
import { ALLERGEN_VOCABULARY, type Allergen } from '../../src/lib/allergens'

const AllergenEnum = z.enum(ALLERGEN_VOCABULARY)

const AllergenSetsSchema = z.object({
  allergens: z.array(AllergenEnum).describe('Allergens CONFIRMED present in the listed ingredients'),
  mayContain: z
    .array(AllergenEnum)
    .describe('Plausible but unconfirmed: typical cross-contamination or ambiguous-ingredient risk'),
  notes: z.string().describe('One short sentence explaining any non-obvious flag; empty string if none'),
})

const HiddenSourceSchema = z.object({
  product: z.string(),
  why: z.string(),
})

const SubstitutionSchema = z.object({
  reason: z.string().describe('Allergy-driven reason, e.g. "peanut-free", "dairy-free"'),
  substitute: z.string(),
  ratio: z.string(),
  notes: z.string(),
})

const IngredientBundleSchema = z.object({
  allergens: z.array(AllergenEnum).describe('Allergens this ingredient itself CONTAINS'),
  mayContain: z
    .array(AllergenEnum)
    .describe('Allergens commonly present via cross-contamination / shared processing'),
  hiddenSources: z
    .array(HiddenSourceSchema)
    .describe('Products that commonly and non-obviously contain this ingredient'),
  crossContamination: z
    .string()
    .describe('Short note on shared-equipment / processing contamination risk; empty string if negligible'),
  substitutions: z
    .array(SubstitutionSchema)
    .describe('Allergy-driven substitutions only (reasons like "peanut-free"); empty if none apply'),
})

export type HiddenSource = z.infer<typeof HiddenSourceSchema>
export type Substitution = z.infer<typeof SubstitutionSchema>

/**
 * Single-model output. There is no `verified` discriminant on purpose — the
 * old union carried one, and keeping it here would assert a cross-check that
 * no longer happens.
 */
export type RecipeAllergenResult = {
  allergens: Allergen[]
  mayContain: Allergen[]
  allergenNotes: string | null
}

export type IngredientAllergenResult = {
  allergenProfile: Allergen[]
  hiddenSources: HiddenSource[]
  crossContamination: string | null
  substitutions: Substitution[]
}

/**
 * One-line reminder for anything that surfaces this data. Printed by the
 * seeders on completion so a run never ends looking like a verification pass.
 */
export const UNVERIFIED_NOTICE =
  "Allergen data is a single AI model's guess and is NOT verified — the allergen disclaimer must render wherever it is shown."

/** Fail closed before spending any tokens: generation must be able to run on Azure. */
export function requireVerifierEnv(): void {
  if (!process.env.AZURE_OPENAI_RESOURCE || !process.env.AZURE_OPENAI_API_KEY) {
    throw new Error(
      '[allergen-verify] AZURE_OPENAI_RESOURCE / AZURE_OPENAI_API_KEY not set — allergen generation is Azure-only (paid frontier model), no free-lane fallback.',
    )
  }
}

const normalizeSet = (values: string[]): Allergen[] =>
  [...new Set(values.map((v) => v.trim().toLowerCase()))].sort() as Allergen[]

const VOCAB_LINE = `Allowed allergen values (use these exact snake_case tokens, nothing else): ${ALLERGEN_VOCABULARY.join(', ')}.`

// The plant-milk rule exists because the 2026-08-05 pilot tagged a *vegan*
// coconut-milk curry as containing "milk". Coconut milk appears across Thai,
// Indian, Malaysian, Indonesian and Caribbean recipes, so one wrong inference
// there mislabels a large share of the corpus.
const RULES_LINE = [
  'Rules: "allergens" = confirmed present in the listed ingredients.',
  '"mayContain" = plausible cross-contamination or ambiguous ingredients only.',
  'Never treat absence as proof an allergen is not present.',
  'wheat implies also flagging gluten_cereals; barley/rye/spelt/oats flag gluten_cereals.',
  '"milk" means DAIRY from an animal only. Plant milks are never "milk":',
  'coconut milk/cream, almond milk, oat milk, rice milk, cashew milk and soy milk',
  'must NOT be flagged as milk. Flag their actual source instead —',
  'soy milk/tofu/tempeh/miso/edamame -> soybeans;',
  'almond or cashew milk -> tree_nuts;',
  'oat milk -> gluten_cereals.',
  'Coconut: never milk. US FDA labels coconut as a tree nut while most tree-nut-allergic',
  'people tolerate it, so put tree_nuts in mayContain for coconut, never in allergens.',
].join(' ')

/**
 * Recipe-level: derive `allergens` / `mayContain` from an ingredient list via
 * the site's standard paid Azure model. Output is unverified — see file header.
 */
export async function verifyRecipeAllergens(input: {
  subject: string
  ingredients: string[]
}): Promise<RecipeAllergenResult> {
  requireVerifierEnv()

  const raw = await batchObject(
    `Identify allergens in this recipe's ingredient list.\n` +
      `Recipe: ${input.subject}\n` +
      `Ingredients:\n${input.ingredients.map((i) => `- ${i}`).join('\n')}\n\n` +
      RULES_LINE,
    AllergenSetsSchema,
    {
      providers: ['azure'],
      tier: 'quality',
      system: 'You are a food-safety annotator for a recipe app. ' + VOCAB_LINE,
    },
  )

  return {
    allergens: normalizeSet(raw.allergens),
    mayContain: normalizeSet(raw.mayContain),
    allergenNotes: raw.notes.trim() || null,
  }
}

/**
 * Ingredient-level: full allergen bundle (profile + hiddenSources +
 * crossContamination + substitutions). Output is unverified — see file header.
 */
export async function verifyIngredientAllergens(input: {
  slug: string
  name: string
  category: string
}): Promise<IngredientAllergenResult> {
  requireVerifierEnv()

  const raw = await batchObject(
    `Produce the allergen profile for a single food ingredient.\n` +
      `Ingredient: ${input.name} (category: ${input.category})\n\n` +
      RULES_LINE +
      ' hiddenSources lists products that commonly and non-obviously contain this ingredient. ' +
      'substitutions are allergy-driven only — swaps that remove an allergen this ingredient carries.',
    IngredientBundleSchema,
    {
      providers: ['azure'],
      tier: 'quality',
      system: 'You are a food-safety annotator for an ingredient encyclopedia. ' + VOCAB_LINE,
    },
  )

  const mayContain = normalizeSet(raw.mayContain)

  return {
    allergenProfile: normalizeSet(raw.allergens),
    hiddenSources: raw.hiddenSources,
    // mayContain has no dedicated Ingredient column — surface it inside the
    // cross-contamination note so the risk is not silently dropped.
    crossContamination:
      [
        raw.crossContamination.trim(),
        mayContain.length ? `May contain (cross-contamination risk): ${mayContain.join(', ')}.` : '',
      ]
        .filter(Boolean)
        .join(' ') || null,
    substitutions: raw.substitutions,
  }
}
