/**
 * Allergen annotation for batch seed/backfill scripts.
 *
 * SINGLE-MODEL as of 2026-08-05 (was a dual-model Azure + claude-opus-5 gate).
 * Allergen sets are now generated by the same paid Azure frontier model every
 * other seeder on this site uses — `tier: 'quality'` → gpt-5.4 — with no
 * independent second-model cross-check.
 *
 * What that changes, stated plainly: this output is a single model's guess.
 * It is NOT verified. Nothing here may be presented to a user as a confirmed
 * allergen-free result. The Recipe timestamp column was renamed
 * `allergenVerifiedAt` → `allergenAnnotatedAt` to match (see prisma/schema.prisma).
 *
 * What has NOT changed, and must not:
 *   - Generation stays on a PAID FRONTIER model with no fallback of any kind —
 *     never the free gpt-oss-120b lane, never Gemini, never the broker's
 *     DeepSeek seeding lane. With no such provider wired (see below) the
 *     model path fails closed with an error rather than silently downgrading.
 *   - The visible allergen disclaimer at src/components/allergen-disclaimer.tsx
 *     (testid `allergen-disclaimer`) must render anywhere these fields are
 *     shown. It names the two failure modes a model cannot see: a misclassified
 *     ingredient, and cross-contamination in the product actually bought.
 *   - The runtime lane in src/lib/ai.ts is untouched by this file.
 *
 * Three-state honesty is retained: `contains` / `may contain` / absent.
 * Absence of a flag is never a "free from X" claim, and callers must render it
 * that way.
 *
 * Vocabulary is the canonical FDA top-9 + EU-14 union in src/lib/allergens.ts.
 *
 * 2026-09-05: Azure is gone from scripts/lib/ai-batch.ts (Cedar: nothing may
 * point at Azure), and the allergen lane may not run on DeepSeek, so the three
 * verify*() functions below have no provider and throw before any call. The
 * live path is the seeders' `--from-file` mode: the paid frontier model
 * (Claude Fable 5.1, in-session) writes the rows and this file's exported
 * schemas + normalize*() helpers validate them, so a file-fed row lands in
 * exactly the shape a model-fed one would have.
 */
import { z } from 'zod'
import { batchObject } from './ai-batch'
import { ALLERGEN_VOCABULARY, type Allergen } from '../../src/lib/allergens'

const AllergenEnum = z.enum(ALLERGEN_VOCABULARY)

const AllergenSetsSchema = z.object({
  allergens: z.array(AllergenEnum).describe('Allergens CONFIRMED present in the listed ingredients'),
  mayContain: z
    .array(AllergenEnum)
    .describe('Plausible but unconfirmed: typical cross-contamination or ambiguous-ingredient risk'),
  notes: z.string().describe('One short sentence explaining any non-obvious flag; empty string if none'),
})

const HiddenSourceSchema = z.object({
  product: z.string(),
  why: z.string(),
})

const SubstitutionSchema = z.object({
  reason: z.string().describe('Allergy-driven reason, e.g. "peanut-free", "dairy-free"'),
  substitute: z.string(),
  ratio: z.string(),
  notes: z.string(),
})

export const IngredientBundleSchema = z.object({
  allergens: z.array(AllergenEnum).describe('Allergens this ingredient itself CONTAINS'),
  mayContain: z
    .array(AllergenEnum)
    .describe('Allergens commonly present via cross-contamination / shared processing'),
  hiddenSources: z
    .array(HiddenSourceSchema)
    .describe('Products that commonly and non-obviously contain this ingredient'),
  crossContamination: z
    .string()
    .describe('Short note on shared-equipment / processing contamination risk; empty string if negligible'),
  substitutions: z
    .array(SubstitutionSchema)
    .describe('Allergy-driven substitutions only (reasons like "peanut-free"); empty if none apply'),
})

const RegulatoryStatusSchema = z.object({
  fda9: z.boolean().describe('Is this allergen one of the FDA "Big 9" major food allergens?'),
  eu14: z.boolean().describe('Is this allergen one of the EU 14 legally declarable allergens?'),
  notes: z
    .string()
    .describe('One short factual sentence on regulatory nuance (e.g. list membership changes); empty string if none'),
})

export const AllergenReferenceSchema = z.object({
  alternateNames: z
    .array(z.string())
    .describe('Other names this allergen appears under on ingredient labels, e.g. "casein", "whey" for milk'),
  regulatoryStatus: RegulatoryStatusSchema,
  hiddenSources: z
    .array(HiddenSourceSchema)
    .describe('Products that commonly and non-obviously contain this allergen'),
  crossReactivity: z
    .string()
    .describe(
      'Other foods/allergens commonly REPORTED as cross-reactive, framed as "commonly reported" never a guarantee; empty string if none well-established',
    ),
  diningOutGuidance: z
    .string()
    .describe(
      'Practical menu-reading guidance for eating out — never medical advice, never a severity or threshold claim',
    ),
})

export type RegulatoryStatus = z.infer<typeof RegulatoryStatusSchema>
export type AllergenReferenceResult = z.infer<typeof AllergenReferenceSchema>

export type HiddenSource = z.infer<typeof HiddenSourceSchema>
export type Substitution = z.infer<typeof SubstitutionSchema>

/**
 * Single-model output. There is no `verified` discriminant on purpose — the
 * old union carried one, and keeping it here would assert a cross-check that
 * no longer happens.
 */
export type RecipeAllergenResult = {
  allergens: Allergen[]
  mayContain: Allergen[]
  allergenNotes: string | null
}

export type IngredientAllergenResult = {
  allergenProfile: Allergen[]
  hiddenSources: HiddenSource[]
  crossContamination: string | null
  substitutions: Substitution[]
}

/**
 * One-line reminder for anything that surfaces this data. Printed by the
 * seeders on completion so a run never ends looking like a verification pass.
 */
export const UNVERIFIED_NOTICE =
  "Allergen data is a single AI model's guess and is NOT verified — the allergen disclaimer must render wherever it is shown."

/**
 * Fail closed before spending any tokens. Always throws since 2026-09-05:
 * Azure was the allergen lane's paid frontier provider and is gone from
 * ai-batch.ts, and batchObject() can now only reach the broker's DeepSeek
 * seeding lane, which this content may never use. Re-pointing the model
 * path needs a paid frontier provider added to ai-batch.ts first — until
 * then the seeders' --from-file mode is the only way allergen rows are written.
 */
export function requireVerifierEnv(): void {
  throw new Error(
    '[allergen-verify] no paid frontier provider is wired for allergen generation — Azure was removed on ' +
      '2026-09-05 and the DeepSeek seeding lane may not write allergen content. Use the seeder\'s ' +
      '--from-file mode (rows written by a paid frontier model in-session) instead.',
  )
}

const normalizeSet = (values: string[]): Allergen[] =>
  [...new Set(values.map((v) => v.trim().toLowerCase()))].sort() as Allergen[]

const VOCAB_LINE = `Allowed allergen values (use these exact snake_case tokens, nothing else): ${ALLERGEN_VOCABULARY.join(', ')}.`

// The plant-milk rule exists because the 2026-08-05 pilot tagged a *vegan*
// coconut-milk curry as containing "milk". Coconut milk appears across Thai,
// Indian, Malaysian, Indonesian and Caribbean recipes, so one wrong inference
// there mislabels a large share of the corpus.
const RULES_LINE = [
  'Rules: "allergens" = confirmed present in the listed ingredients.',
  '"mayContain" = plausible cross-contamination or ambiguous ingredients only.',
  'Never treat absence as proof an allergen is not present.',
  'wheat implies also flagging gluten_cereals; barley/rye/spelt/oats flag gluten_cereals.',
  '"milk" means DAIRY from an animal only. Plant milks are never "milk":',
  'coconut milk/cream, almond milk, oat milk, rice milk, cashew milk and soy milk',
  'must NOT be flagged as milk. Flag their actual source instead —',
  'soy milk/tofu/tempeh/miso/edamame -> soybeans;',
  'almond or cashew milk -> tree_nuts;',
  'oat milk -> gluten_cereals.',
  'Coconut: never milk. US FDA labels coconut as a tree nut while most tree-nut-allergic',
  'people tolerate it, so put tree_nuts in mayContain for coconut, never in allergens.',
].join(' ')

/**
 * Recipe-level: derive `allergens` / `mayContain` from an ingredient list via
 * the site's standard paid Azure model. Output is unverified — see file header.
 */
export async function verifyRecipeAllergens(input: {
  subject: string
  ingredients: string[]
}): Promise<RecipeAllergenResult> {
  requireVerifierEnv()

  const raw = await batchObject(
    `Identify allergens in this recipe's ingredient list.\n` +
      `Recipe: ${input.subject}\n` +
      `Ingredients:\n${input.ingredients.map((i) => `- ${i}`).join('\n')}\n\n` +
      RULES_LINE,
    AllergenSetsSchema,
    {
      // Unreachable until requireVerifierEnv() is re-pointed at a paid frontier provider.
      // No `providers` on purpose: naming the broker here would read as consent to DeepSeek.
      tier: 'quality',
      system: 'You are a food-safety annotator for a recipe app. ' + VOCAB_LINE,
    },
  )

  return {
    allergens: normalizeSet(raw.allergens),
    mayContain: normalizeSet(raw.mayContain),
    allergenNotes: raw.notes.trim() || null,
  }
}

// Rules specific to the standalone Allergen reference table (the encyclopedia
// page about the allergen itself, not a specific food or recipe). Layered on
// top of RULES_LINE's plant-milk correction, which still applies wherever
// hiddenSources mentions milk-adjacent products.
const ALLERGEN_REFERENCE_RULES = [
  'This is public reference content about the allergen itself, not a specific food or recipe.',
  'NEVER use the phrase "free from" anywhere in any field.',
  'NEVER state a medical threshold — no dose, trace amount, or parts-per-million figure that would or would not trigger a reaction.',
  'NEVER make a reaction-severity or likelihood claim (e.g. "usually causes anaphylaxis", "mild in most people") — severity varies per person and is a medical question, not a labeling one.',
  'diningOutGuidance is practical menu-reading advice only (what to ask staff, what to watch for on a menu) — never medical advice, never a substitute for talking to a doctor or allergist, and say so is out of scope rather than implying safety.',
  'crossReactivity may name other foods/allergens with a commonly reported cross-reactive relationship, framed as "commonly reported" — never as a guarantee or a diagnosis. Leave it an empty string if nothing is well-established.',
  'regulatoryStatus.fda9/eu14 are factual list-membership flags only, not a presence/absence claim about any product.',
].join(' ')

/**
 * Allergen-reference-level: the standalone Allergen table's encyclopedia
 * content (regulatory status, alternate label names, hidden sources, cross
 * reactivity, dining-out guidance) for one canonical allergen token. Output is
 * unverified — see file header. Same paid-Azure-only contract as the two
 * functions above: requireVerifierEnv() throws before any call is made.
 */
export async function verifyAllergenReference(input: {
  slug: string
  name: string
}): Promise<AllergenReferenceResult> {
  requireVerifierEnv()

  const raw = await batchObject(
    `Produce public reference content for a food allergen encyclopedia page.\n` +
      `Allergen: ${input.name} (canonical token: ${input.slug})\n\n` +
      ALLERGEN_REFERENCE_RULES,
    AllergenReferenceSchema,
    {
      // Unreachable until requireVerifierEnv() is re-pointed at a paid frontier provider.
      // No `providers` on purpose: naming the broker here would read as consent to DeepSeek.
      tier: 'quality',
      system:
        'You are a food-allergen reference-content writer for a public encyclopedia page. ' +
        'You write descriptive, non-medical reference content only. ' +
        VOCAB_LINE,
    },
  )

  return normalizeAllergenReference(raw)
}

/** Post-processing shared by the model path and `--from-file`: trim, dedupe, drop blanks. */
export function normalizeAllergenReference(raw: z.infer<typeof AllergenReferenceSchema>): AllergenReferenceResult {
  return {
    alternateNames: [...new Set(raw.alternateNames.map((n) => n.trim()).filter(Boolean))],
    regulatoryStatus: { ...raw.regulatoryStatus, notes: raw.regulatoryStatus.notes.trim() },
    hiddenSources: raw.hiddenSources.map((h) => ({ product: h.product.trim(), why: h.why.trim() })),
    crossReactivity: raw.crossReactivity.trim(),
    diningOutGuidance: raw.diningOutGuidance.trim(),
  }
}

/**
 * Ingredient-level: full allergen bundle (profile + hiddenSources +
 * crossContamination + substitutions). Output is unverified — see file header.
 */
export async function verifyIngredientAllergens(input: {
  slug: string
  name: string
  category: string
}): Promise<IngredientAllergenResult> {
  requireVerifierEnv()

  const raw = await batchObject(
    `Produce the allergen profile for a single food ingredient.\n` +
      `Ingredient: ${input.name} (category: ${input.category})\n\n` +
      RULES_LINE +
      ' hiddenSources lists products that commonly and non-obviously contain this ingredient. ' +
      'substitutions are allergy-driven only — swaps that remove an allergen this ingredient carries.',
    IngredientBundleSchema,
    {
      // Unreachable until requireVerifierEnv() is re-pointed at a paid frontier provider.
      // No `providers` on purpose: naming the broker here would read as consent to DeepSeek.
      tier: 'quality',
      system: 'You are a food-safety annotator for an ingredient encyclopedia. ' + VOCAB_LINE,
    },
  )

  return normalizeIngredientBundle(raw)
}

/** Post-processing shared by the model path and `--from-file`. */
export function normalizeIngredientBundle(raw: z.infer<typeof IngredientBundleSchema>): IngredientAllergenResult {
  const mayContain = normalizeSet(raw.mayContain)

  return {
    allergenProfile: normalizeSet(raw.allergens),
    hiddenSources: raw.hiddenSources.map((h) => ({ product: h.product.trim(), why: h.why.trim() })),
    // mayContain has no dedicated Ingredient column — surface it inside the
    // cross-contamination note so the risk is not silently dropped.
    crossContamination:
      [
        raw.crossContamination.trim(),
        mayContain.length ? `May contain (cross-contamination risk): ${mayContain.join(', ')}.` : '',
      ]
        .filter(Boolean)
        .join(' ') || null,
    substitutions: raw.substitutions,
  }
}
